Source = https://www.machinelearningplus.com/python/101-numpy-exercises-python/

# 1. Import numpy as np and see the version
Difficulty Level: L1<br>

> Q. Import numpy as np and print the version number.

In [1]:
# My solution
import numpy as np

In [2]:
# Solution
import numpy as np
print(np.__version__)

1.21.6


# 2. How to create a 1D array?
Difficulty Level: L1<br>

Q. Create a 1D array of numbers from 0 to 9

> Desired output:
    #> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# My solution
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Solution
arr = np.arange(10)
arr

# 3. How to create a boolean array?
Difficulty Level: L1<br>

Q. Create a 3×3 numpy array of all True

In [6]:
# My solution
arr = np.full((3,3), True)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
# Solution
np.full((3, 3), True, dtype=bool)

# Alternate method
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 4. How to extract items that satisfy a given condition from 1D array?
Difficulty Level: L1<br>

Q. Extract all odd numbers from `arr`<br>

> input:<br>

    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> Desired output:<br>

    #> array([1, 3, 5, 7, 9])



In [10]:
# My solution
arr = np.array([0,1,2,3,4,5,6,7,8,9])

arr[(arr%2) == 1]

array([1, 3, 5, 7, 9])

In [ ]:
# Solution
arr[arr % 2 == 1]

# 5. How to replace items that satisfy a condition with another value in numpy array?
Difficulty Level: L1<br>

Q. Replace all odd numbers in arr with -1

> Input:

    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> Desired Output:

    #>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [14]:
# My solution
arr = np.array([0,1,2,3,4,5,6,7,8,9])

arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
# Solution
arr[arr % 2 == 1] = -1
arr